In [4]:
import pandas as pd

df = pd.read_csv("datasets/laptops.csv")
df

,brand,model,cpu,gpu,ram_gb,storage_gb,price_usd
0,Acer,Aspire 5,i3-1115G4,Integrated,8,256,410
1,Acer,Nitro 5,i5-11400H,RTX 3050,16,512,850
2,Asus,VivoBook 14,R5-5500U,Integrated,8,512,520
3,Asus,ROG Strix G15,R7-5800H,RTX 3060,16,512,1400
4,Dell,Inspiron 3511,i3-1115G4,Integrated,8,256,430
5,Dell,G15,i5-12500H,RTX 3050 Ti,16,512,1150
6,HP,Pavilion 14,i5-1135G7,Integrated,8,512,600
7,HP,Victus 16,R5-5600H,RTX 3050,16,512,980
8,Lenovo,IdeaPad 3,R3-5300U,Integrated,8,256,400
9,Lenovo,Legion 5,R7-5800H,RTX 3060,16,512,1350
10,MSI,GF63 Thin,i5-11400H,GTX 1650,8,512,750
11,MSI,Cyborg 15,i7-12650H,RTX 4050,16,512,1500

In [5]:
# cek jumlah baris dan kolom
print(f"Shape: {df.shape}")
# cek 5 data teratas
display(df.head())
# cek info tipe data
df.info()
# cek apakah ada nilai kosong
df.isnull().sum()

Shape: (12, 7)

  brand          model        cpu         gpu  ram_gb  storage_gb  price_usd
0  Acer       Aspire 5  i3-1115G4  Integrated       8         256        410
1  Acer        Nitro 5  i5-11400H    RTX 3050      16         512        850
2  Asus    VivoBook 14   R5-5500U  Integrated       8         512        520
3  Asus  ROG Strix G15   R7-5800H    RTX 3060      16         512       1400
4  Dell  Inspiron 3511  i3-1115G4  Integrated       8         256        430

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   brand       12 non-null     object
 1   model       12 non-null     object
 2   cpu         12 non-null     object
 3   gpu         12 non-null     object
 4   ram_gb      12 non-null     int64
 5   storage_gb  12 non-null     int64
 6   price_usd   12 non-null     int64
dtypes: int64(3), object(4)
memory usage: 804.0+ bytes

brand         0
model         0
cpu           0
gpu           0
ram_gb        0
storage_gb    0
price_usd     0
dtype: int64

In [3]:
# Pastikan dataset ter-load — jalankan ini dulu sebelum preprocessing
import pandas as pd
from pathlib import Path

print("Current working dir:", Path.cwd())
print("Checking dataset file exists:", Path("datasets/laptops.csv").exists())

# Load dataset
df = pd.read_csv("datasets/laptops.csv")

# Cek singkat
print(f"Loaded df shape: {df.shape}")
display(df.head())

Current working dir: c:\Users\dzikr\Projects\laptop-reco\ml2
Checking dataset file exists: True
Loaded df shape: (12, 7)

  brand          model        cpu         gpu  ram_gb  storage_gb  price_usd
0  Acer       Aspire 5  i3-1115G4  Integrated       8         256        410
1  Acer        Nitro 5  i5-11400H    RTX 3050      16         512        850
2  Asus    VivoBook 14   R5-5500U  Integrated       8         512        520
3  Asus  ROG Strix G15   R7-5800H    RTX 3060      16         512       1400
4  Dell  Inspiron 3511  i3-1115G4  Integrated       8         256        430

In [4]:
# Langkah 8: Preprocessing pipeline (fix untuk scikit-learn baru)
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

X = df.drop(columns=["price_usd"])
y = df["price_usd"]

cat_cols = ["brand", "cpu", "gpu", "model"]
num_cols = ["ram_gb", "storage_gb"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols),
        ("num", StandardScaler(), num_cols)
    ],
    remainder="drop"
)

pipeline = Pipeline([
    ("preprocessor", preprocessor)
])

X_pre = pipeline.fit_transform(X)

# ambil nama kolom OHE
ohe = pipeline.named_steps["preprocessor"].named_transformers_["cat"]
ohe_feature_names = ohe.get_feature_names_out(cat_cols)
all_feature_names = list(ohe_feature_names) + num_cols

print(f"Original X shape: {X.shape}")
print(f"Transformed X shape: {X_pre.shape}\n")

X_pre_df = pd.DataFrame(X_pre, columns=all_feature_names)
display(X_pre_df.head())

# simpan pipeline
import os, joblib
os.makedirs("artifacts", exist_ok=True)
joblib.dump(pipeline, "artifacts/preprocessor_pipeline.joblib")
print("\nPreprocessor saved to artifacts/preprocessor_pipeline.joblib")

Original X shape: (12, 6)
Transformed X shape: (12, 35)

,brand_Acer,brand_Asus,brand_Dell,brand_HP,brand_Lenovo,brand_MSI,cpu_R3-5300U,cpu_R5-5500U,cpu_R5-5600H,cpu_R7-5800H,...,model_IdeaPad 3,model_Inspiron 3511,model_Legion 5,model_Nitro 5,model_Pavilion 14,model_ROG Strix G15,model_Victus 16,model_VivoBook 14,ram_gb,storage_gb
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.732051
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.577350
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0,0.577350
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.577350
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.732051

Preprocessor saved to artifacts/preprocessor_pipeline.joblib

In [5]:
# Jalankan ini di sel baru — buat folder artifacts dan simpan pipeline ke sana
import os
import joblib

# Pastikan kita berada di working dir yang sama seperti notebook
from pathlib import Path
print("Working dir:", Path.cwd())

# Buat folder artifacts di working dir (jika belum ada)
os.makedirs("artifacts", exist_ok=True)

# Simpan pipeline ke artifacts
save_path = Path("artifacts") / "preprocessor_pipeline.joblib"
joblib.dump(pipeline, save_path)

# Verifikasi file tersimpan
print("Saved to:", save_path.resolve())
print("Exists?", save_path.exists())

Working dir: c:\Users\dzikr\Projects\laptop-reco\ml2
Saved to: C:\Users\dzikr\Projects\laptop-reco\ml2\artifacts\preprocessor_pipeline.joblib
Exists? True

In [6]:
# Langkah 9: Train simple RandomForest regressor, evaluasi, dan simpan model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import Pipeline as SKPipeline
import joblib, os
from math import sqrt

# 1) Siapkan X, y (pastikan df ada)
X = df.drop(columns=["price_usd"])
y = df["price_usd"]

# 2) Split data (train / test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3) Buat pipeline lengkap: preprocessor (yang sudah kita definisikan sebagai 'pipeline') + model
# Note: 'pipeline' sebelumnya hanya berisi preprocessor. Kita wrapping jadi model_pipeline.
model_pipeline = SKPipeline([
    ("preprocessor", pipeline.named_steps["preprocessor"]),  # pakai preprocessor yang sudah fit/fit-able
    ("model", RandomForestRegressor(n_estimators=100, random_state=42))
])

# 4) Fit model
model_pipeline.fit(X_train, y_train)

# 5) Predict & evaluasi
y_pred = model_pipeline.predict(X_test)
rmse = sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Train size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")
print(f"RMSE on test: {rmse:.2f} (USD)")
print(f"R^2 on test : {r2:.3f}")

# 6) Simpan model (beserta preprocessor yang tersimpan terpisah)
os.makedirs("artifacts", exist_ok=True)
model_path = "artifacts/model_randomforest.joblib"
joblib.dump(model_pipeline, model_path)
print(f"\nModel saved to: {model_path}")

Train size: 9 | Test size: 3
RMSE on test: 135.18 (USD)
R^2 on test : 0.879

Model saved to: artifacts/model_randomforest.joblib

In [7]:
# Langkah 10: Load model dan buat fungsi inference sederhana
import joblib
import pandas as pd
from pathlib import Path

# 1) Load model pipeline yang sudah kita simpan
model_path = Path("artifacts") / "model_randomforest.joblib"
assert model_path.exists(), f"Model tidak ditemukan di {model_path.resolve()}"
model_pipeline = joblib.load(model_path)

# 2) Kolom input yang diperlukan (urutan tidak krusial karena kita pakai DataFrame)
input_columns = ["brand", "model", "cpu", "gpu", "ram_gb", "storage_gb"]

# 3) Fungsi prediksi harga
def predict_price(spec: dict) -> float:
    """
    spec: dict, contoh:
      {
        "brand": "Acer",
        "model": "Nitro 5",
        "cpu": "i5-11400H",
        "gpu": "RTX 3050",
        "ram_gb": 16,
        "storage_gb": 512
      }
    Mengembalikan: prediksi harga (float, dalam USD)
    """
    # Buat DataFrame 1 baris dari dict (isi kolom yang hilang dengan None kalau perlu)
    row = {col: spec.get(col, None) for col in input_columns}
    df_input = pd.DataFrame([row], columns=input_columns)
    
    # Predict (pipeline sudah menangani encoding & scaling)
    pred = model_pipeline.predict(df_input)
    return float(pred[0])

# 4) Contoh pemakaian — ganti dengan spesifikasi lain kalau mau
example_spec = {
    "brand": "Acer",
    "model": "Nitro 5",
    "cpu": "i5-11400H",
    "gpu": "RTX 3050",
    "ram_gb": 16,
    "storage_gb": 512
}

pred_price = predict_price(example_spec)
print(f"Predicted price for example spec: ${pred_price:.2f} (USD)")

Predicted price for example spec: $982.80 (USD)

In [8]:
# Langkah 11: Fungsi rekomendasi sederhana berbasis kebutuhan + budget
import numpy as np
import pandas as pd

# Pastikan df dan model_pipeline sudah ada di memory
assert 'df' in globals(), "df belum ter-load. Jalankan sel load dataset dulu."
assert 'model_pipeline' in globals(), "model_pipeline belum ter-load. Jalankan sel load model dulu."

def _text_match_score(text, keywords):
    """Simple helper: return score 1.0 if any keyword in text (case-ins), else 0.0"""
    if not keywords:
        return 0.0
    txt = str(text).lower()
    for kw in keywords:
        if kw.lower() in txt:
            return 1.0
    return 0.0

def recommend_laptops(user_need: dict, budget: float = None, top_n: int = 5):
    """
    user_need: dict with optional keys:
      - min_ram (int, GB)
      - prefer_gpu (list of keywords, e.g. ['rtx', 'gtx', 'integrated'])
      - prefer_cpu (list of keywords, e.g. ['i5','ryzen 5','m1'])
      - usage (optional string, e.g. 'office','gaming','editing')  -- not used directly but for explanation
    budget: maximal budget user (in same unit as df.price_usd). If None, budget ignored for price scoring.
    top_n: number of recommendations to return.
    
    Returns: DataFrame of top_n rows with columns: id, brand, model, price_usd, score, reason
    """
    # copy dataset so we don't mutate original
    table = df.copy().reset_index(drop=True)
    
    # if dataset lacks price_usd predicted by model, use actual price_usd; we still compute pred_price for checking closeness if budget provided
    try:
        pred_prices = model_pipeline.predict(table.drop(columns=["price_usd"]))
    except Exception:
        # fallback: use actual price column if predict fails
        pred_prices = table["price_usd"].values
    
    table["_pred_price"] = pred_prices.astype(float)
    
    # compute simple components
    min_ram = user_need.get("min_ram", 0)
    prefer_gpu = user_need.get("prefer_gpu", [])
    prefer_cpu = user_need.get("prefer_cpu", [])
    
    # column checks
    if "ram_gb" not in table.columns:
        table["ram_gb"] = 0
    if "gpu" not in table.columns:
        table["gpu"] = ""
    if "cpu" not in table.columns:
        table["cpu"] = ""
    
    # component scores (0..1)
    # ram_score: 1 if ram >= required, else ram/min_required (clipped)
    def ram_score(r):
        if min_ram <= 0:
            return 0.5  # neutral if user didn't request
        return float(min(1.0, r / float(min_ram))) if r > 0 else 0.0
    
    table["_ram_score"] = table["ram_gb"].apply(ram_score)
    table["_gpu_score"] = table["gpu"].apply(lambda g: _text_match_score(g, prefer_gpu) if prefer_gpu else 0.5)
    table["_cpu_score"] = table["cpu"].apply(lambda c: _text_match_score(c, prefer_cpu) if prefer_cpu else 0.5)
    
    # price closeness score: higher is better (1 = exact budget, 0 = very far)
    if budget:
        max_span = max(table["_pred_price"].max(), budget) - min(table["_pred_price"].min(), budget)
        max_span = max(max_span, 1.0)
        table["_price_diff"] = table["_pred_price"].apply(lambda p: abs(p - budget))
        table["_price_score"] = table["_price_diff"].apply(lambda d: 1.0 - min(1.0, d / max_span))
    else:
        table["_price_score"] = 0.5  # neutral if no budget provided
    
    # combine scores with weights (you can tune these weights later)
    w_price = 0.4
    w_gpu = 0.3
    w_cpu = 0.15
    w_ram = 0.15
    
    table["_score"] = (
        w_price * table["_price_score"] +
        w_gpu * table["_gpu_score"] +
        w_cpu * table["_cpu_score"] +
        w_ram * table["_ram_score"]
    )
    
    # format reason string for top candidates
    def make_reason(row):
        reasons = []
        reasons.append(f"Price ~ ${row['_pred_price']:.0f} (dataset price ${row['price_usd']})")
        if row["_gpu_score"] >= 0.99:
            reasons.append("GPU matches preference")
        elif row["_gpu_score"] >= 0.5:
            reasons.append("GPU partly suitable")
        else:
            reasons.append("GPU not prioritized")
        if row["_cpu_score"] >= 0.99:
            reasons.append("CPU matches preference")
        elif row["_cpu_score"] >= 0.5:
            reasons.append("CPU partly suitable")
        else:
            reasons.append("CPU not prioritized")
        if row["_ram_score"] >= 0.99:
            reasons.append(f"RAM >= {user_need.get('min_ram', row['ram_gb'])}GB")
        else:
            reasons.append(f"RAM {int(row['ram_gb'])}GB")
        return "; ".join(reasons)
    
    table["reason"] = table.apply(make_reason, axis=1)
    
    # pick top_n by score, and present relevant columns
    out_cols = ["brand", "model", "cpu", "gpu", "ram_gb", "storage_gb", "price_usd", "_pred_price", "_score", "reason"]
    result = table.sort_values("_score", ascending=False).head(top_n)[out_cols].reset_index(drop=True)
    result = result.rename(columns={"_pred_price": "pred_price", "_score": "score"})
    # round score to 3 decimals
    result["score"] = result["score"].round(3)
    result["pred_price"] = result["pred_price"].round(2)
    return result

# Contoh pemakaian:
user_need = {
    "min_ram": 16,
    "prefer_gpu": ["rtx", "gtx"],       # keywords; 'rtx' matches 'RTX 3050' dll.
    "prefer_cpu": ["i5", "ryzen 5"]     # keywords
}
budget = 1200  # USD

rec = recommend_laptops(user_need=user_need, budget=budget, top_n=5)
rec

,brand,model,cpu,gpu,ram_gb,storage_gb,price_usd,pred_price,score,reason
0,Dell,G15,i5-12500H,RTX 3050 Ti,16,512,1150,1142.4,0.973,Price ~ $1142 (dataset price $1150); GPU match...
1,Acer,Nitro 5,i5-11400H,RTX 3050,16,512,850,982.8,0.896,Price ~ $983 (dataset price $850); GPU matches...
2,Lenovo,Legion 5,R7-5800H,RTX 3060,16,512,1350,1224.0,0.839,Price ~ $1224 (dataset price $1350); GPU match...
3,Asus,ROG Strix G15,R7-5800H,RTX 3060,16,512,1400,1248.5,0.827,Price ~ $1248 (dataset price $1400); GPU match...
4,MSI,GF63 Thin,i5-11400H,GTX 1650,8,512,750,921.0,0.792,Price ~ $921 (dataset price $750); GPU matches...